[package]
name = "basic_receiving_actor"
version = "0.1.0"
edition = "2021"

[dependencies]
frc46_token = { version = "0.2.0", path = "../../../../frc46_token" }
frc42_dispatch = { path = "../../../../frc42_dispatch" }
fvm_actor_utils = { version = "0.1.0", path = "../../../../fvm_actor_utils" }
fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding = "0.2.2"
fvm_sdk = { version = "2.0.0-alpha.2" }
fvm_shared = { version = "2.0.0-alpha.2" }

[build-dependencies]
wasm-builder = "3.0"