[package]
name = "greeter"
version = "0.1.0"
edition = "2021"

[dependencies]
frc42_dispatch = { path = "../../frc42_dispatch" }
fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding = "=0.2.3"
fvm_sdk =  "=2.2.0"
fvm_shared = { version = "2.0.0" }

[dev-dependencies]
cid = { version = "0.8.5", default-features = false }
fvm = { version = "2.0.0", default-features = false }
fvm_integration_tests = "2.0.0-alpha.1"
actors-v10 = { package = "fil_builtin_actors_bundle", git = "https://github.com/filecoin-project/builtin-actors", rev = "324b966847d7a5fd691a2ea804521ab4698e7b67" }

[build-dependencies]
substrate-wasm-builder = "4.0"
