[package]
name = "frc46_factory_token"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cid = { workspace = true }
frc42_dispatch = { workspace = true }
frc46_token = { workspace = true }
fvm_actor_utils = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }
multihash-codetable = { workspace = true }
serde = { workspace = true }
serde_tuple = { workspace = true }
thiserror = { workspace = true }
token_impl = { path = "token_impl" }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
