[package]
name = "frc46_test_actor"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
frc46_token = { workspace = true }
frc42_dispatch = { workspace = true }
frc53_nft = { workspace = true }
fvm_actor_utils = { workspace = true }

cid = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }
serde = { workspace = true }
serde_tuple = { workspace = true }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
